### ISSUE TITLE
Fetching package dependencies

### ISSUE THREAD

**Issue by cadojo** [jwodder/pypi-simple#6]
Is there any supported way to fetch package dependencies through this library? As in the [JSON API](https://wiki.python.org/moin/PyPIJSON)?

**Comment by jwodder** [comment]
The only way that such data can be exposed via the Simple API is via download links to packages' Core Metadata (see [PEP 658](https://peps.python.org/pep-0658/) along with the `has_metadata`, `metadata_url`, and `metadata_digests` fields of `DistributionPackage`).  Unfortunately, it does not appear that Warehouse has implemented PEP 658 yet, so the Simple API (and thus this library) cannot yet be used to obtain package metadata.

**Comment by diazona** [comment]
I randomly came across this and just wanted to note that it looks like PyPI currently _does_ implement PEP 658 for some recent releases. E.g the last four versions of [`setuptools`](https://pypi.org/simple/setuptools/) have `data-dist-info-metadata` (and `data-core-metadata`). It'd be handy if that could be exposed through this package since as far as I can tell, that information doesn't seem to show up in the JSON API. (I haven't done the research to know whether the JSON API doesn't support it or if PyPI simply hasn't implemented that.)

Would it help to offer a PR?

**Comment by jwodder** [comment]
`pypi-simple` has supported PEP 658 since v0.9.0, released in August 2021, which added the `has_metadata`, `metadata_url`, and `metadata_digests` attributes to `DistributionPackage`.

Additionally, the just-released v1.3.0 of `pypi-simple` — in addition to updating for PEP 714 — adds a `get_package_metadata()` method for downloading metadata, and there is an example of using it to fetch dependencies in the documentation: <https://pypi-simple.readthedocs.io/en/stable/examples.html#getting-a-project-s-dependencies>.

**Comment by diazona** [comment]
Ah, thanks. For some reason I must have missed that when commenting.
